import { AtlasTemplate } from "./block-types";

const NOW = new Date().toISOString();

export const DEFAULT_TEMPLATES: AtlasTemplate[] = [
	{
		id: "daily",
		name: "Daily Log",
		icon: "📓",
		description: "Log diário com plano, decisões, escalations, sentiment, follow-ups",
		category: "daily",
		variables: [
			{ key: "data", label: "Data", required: true },
			{ key: "dataPretty", label: "Data formatada", required: false },
		],
		blocks: [
			{
				id: "fm",
				kind: "frontmatter",
				fields: {
					date: "{{data}}",
					type: "daily",
					mood: "",
					energy: "",
					status: "draft",
					tags: "[daily]",
				},
			},
			{ id: "h1", kind: "heading", level: 1, icon: "📓", text: "Daily Log — {{dataPretty}}" },
			{ id: "h2-plan", kind: "heading", level: 2, icon: "🌅", text: "Plano da manhã" },
			{
				id: "list-plan",
				kind: "list",
				style: "checkbox",
				items: ["", "", ""],
			},
			{ id: "h2-tasks", kind: "heading", level: 2, icon: "⚡", text: "Tasks vencendo hoje" },
			{
				id: "code-tasks",
				kind: "code",
				lang: "dataview",
				code: "TASK\nWHERE !completed AND due <= date(today)\nSORT priority DESC, due ASC",
			},
			{ id: "h2-decisions", kind: "heading", level: 2, icon: "📝", text: "Decisões" },
			{ id: "text-dec", kind: "text", text: "-" },
			{ id: "h2-blockers", kind: "heading", level: 2, icon: "🧱", text: "Blockers" },
			{ id: "text-block", kind: "text", text: "-" },
			{ id: "h2-sentiment", kind: "heading", level: 2, icon: "🌡️", text: "Sentiment do time" },
			{ id: "text-sent", kind: "text", text: "-" },
			{ id: "h2-followup", kind: "heading", level: 2, icon: "🔁", text: "Follow-ups" },
			{
				id: "task-fol",
				kind: "tasks-placeholder",
				prefix: "#followup",
				dueDateOffset: 1,
			},
			{ id: "h2-refl", kind: "heading", level: 2, icon: "💭", text: "Reflexão" },
			{ id: "text-refl", kind: "text", text: "-" },
		],
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: "1on1-grow",
		name: "1:1 GROW",
		icon: "🤝",
		description: "Sessão de 1:1 com framework GROW (Goal/Reality/Options/Will)",
		category: "meeting",
		variables: [
			{ key: "pessoa", label: "Pessoa", required: true, promptOnUse: true },
			{ key: "data", label: "Data", required: true },
		],
		blocks: [
			{
				id: "fm",
				kind: "frontmatter",
				fields: {
					type: "1on1",
					person: "{{pessoa}}",
					date: "{{data}}",
					framework: "GROW",
					status: "scheduled",
					tags: "[1on1]",
				},
			},
			{ id: "h1", kind: "heading", level: 1, text: "1:1 com [[{{pessoa}}]] — {{data}}" },
			{ id: "atlas", kind: "atlas-brief" },
			{ id: "h-goal", kind: "heading", level: 2, icon: "🎯", text: "Goal" },
			{ id: "t-goal", kind: "text", text: "_O que ela quer alcançar?_\n- " },
			{ id: "h-reality", kind: "heading", level: 2, icon: "🔍", text: "Reality" },
			{ id: "t-real", kind: "text", text: "_Onde está, obstáculos?_\n- " },
			{ id: "h-options", kind: "heading", level: 2, icon: "💡", text: "Options" },
			{ id: "t-opt", kind: "text", text: "_Que alternativas exploramos?_\n- " },
			{ id: "h-will", kind: "heading", level: 2, icon: "🏃", text: "Will" },
			{ id: "t-will", kind: "text", text: "_Em que ela vai se comprometer?_\n- " },
			{ id: "h-actions", kind: "heading", level: 2, icon: "✅", text: "Action Items" },
			{
				id: "task-action",
				kind: "tasks-placeholder",
				owner: "{{pessoa}}",
				dueDateOffset: 7,
			},
			{ id: "h-follow", kind: "heading", level: 2, icon: "🔁", text: "Meus follow-ups" },
			{
				id: "task-fol",
				kind: "tasks-placeholder",
				owner: "eu",
				dueDateOffset: 7,
			},
			{ id: "h-themes", kind: "heading", level: 2, icon: "🏷️", text: "Themes" },
			{ id: "tags", kind: "tags", tags: ["theme/"] },
			{ id: "h-recall", kind: "heading", level: 2, icon: "📌", text: "Recall (próxima sessão)" },
			{ id: "t-recall", kind: "text", text: "- " },
		],
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: "1on1-clear",
		name: "1:1 CLEAR",
		icon: "🤝",
		description: "1:1 com framework CLEAR (Contract/Listen/Explore/Action/Review)",
		category: "meeting",
		variables: [
			{ key: "pessoa", label: "Pessoa", required: true, promptOnUse: true },
			{ key: "data", label: "Data", required: true },
		],
		blocks: [
			{
				id: "fm",
				kind: "frontmatter",
				fields: {
					type: "1on1",
					person: "{{pessoa}}",
					date: "{{data}}",
					framework: "CLEAR",
					tags: "[1on1]",
				},
			},
			{ id: "h1", kind: "heading", level: 1, text: "1:1 com [[{{pessoa}}]] — {{data}}" },
			{ id: "atlas", kind: "atlas-brief" },
			{ id: "h-c", kind: "heading", level: 2, icon: "📝", text: "Contract" },
			{ id: "t-c", kind: "text", text: "_O que vamos discutir?_\n- " },
			{ id: "h-l", kind: "heading", level: 2, icon: "👂", text: "Listen" },
			{ id: "t-l", kind: "text", text: "_O que ela está dizendo (e não dizendo)?_\n- " },
			{ id: "h-e", kind: "heading", level: 2, icon: "🔎", text: "Explore" },
			{ id: "t-e", kind: "text", text: "_Perspectivas, hipóteses_\n- " },
			{ id: "h-a", kind: "heading", level: 2, icon: "🏃", text: "Action" },
			{ id: "t-a", kind: "text", text: "_O que vai fazer_\n- " },
			{ id: "h-r", kind: "heading", level: 2, icon: "🔄", text: "Review" },
			{ id: "t-r", kind: "text", text: "_Aprendizados_\n- " },
		],
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: "coaching-session",
		name: "Sessão de Coaching",
		icon: "🎓",
		description: "Sessão profissional de coaching com confidencialidade",
		category: "coaching",
		variables: [
			{ key: "coachee", label: "Coachee", required: true, promptOnUse: true },
			{ key: "data", label: "Data", required: true },
		],
		blocks: [
			{
				id: "fm",
				kind: "frontmatter",
				fields: {
					type: "coaching-session",
					coachee: "{{coachee}}",
					date: "{{data}}",
					framework: "GROW",
					confidential: "true",
					tags: "[coaching, confidential]",
				},
			},
			{ id: "h1", kind: "heading", level: 1, text: "Sessão — [[{{coachee}}]] — {{data}}" },
			{
				id: "warn",
				kind: "callout",
				type: "warning",
				title: "CONFIDENCIAL",
				text: "Vault de coaching · LGPD/ICF · Não compartilhar.",
			},
			{ id: "h-contract", kind: "heading", level: 2, icon: "🎯", text: "Objetivo do contrato" },
			{ id: "t-contract", kind: "text", text: "- " },
			{ id: "atlas", kind: "atlas-brief" },
			{ id: "h-checkin", kind: "heading", level: 2, icon: "🤝", text: "Check-in" },
			{ id: "t-ci", kind: "text", text: "- " },
			{ id: "h-foco", kind: "heading", level: 2, icon: "🎯", text: "Foco da sessão" },
			{ id: "t-foco", kind: "text", text: "- " },
			{ id: "h-r", kind: "heading", level: 2, icon: "🔍", text: "Reality" },
			{ id: "t-r", kind: "text", text: "- " },
			{ id: "h-o", kind: "heading", level: 2, icon: "💡", text: "Options" },
			{ id: "t-o", kind: "text", text: "- " },
			{ id: "h-w", kind: "heading", level: 2, icon: "🏃", text: "Will" },
			{ id: "t-w", kind: "text", text: "- " },
			{ id: "h-insights", kind: "heading", level: 2, icon: "✨", text: "Insights" },
			{ id: "t-i", kind: "text", text: "- " },
			{ id: "h-pat", kind: "heading", level: 2, icon: "🪞", text: "Padrões observados" },
			{ id: "t-p", kind: "text", text: "_Hipóteses para sessões futuras_\n- " },
		],
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: "meeting",
		name: "Reunião",
		icon: "📋",
		description: "Notas de reunião (geral)",
		category: "meeting",
		variables: [
			{ key: "titulo", label: "Título", required: true, promptOnUse: true },
			{ key: "data", label: "Data", required: true },
		],
		blocks: [
			{
				id: "fm",
				kind: "frontmatter",
				fields: {
					type: "meeting",
					title: "{{titulo}}",
					date: "{{data}}",
					attendees: "[]",
					tags: "[meeting]",
				},
			},
			{ id: "h1", kind: "heading", level: 1, icon: "📋", text: "{{titulo}}" },
			{ id: "h-att", kind: "heading", level: 2, icon: "👥", text: "Participantes" },
			{ id: "t-att", kind: "text", text: "- " },
			{ id: "h-ag", kind: "heading", level: 2, icon: "📝", text: "Agenda" },
			{ id: "list-ag", kind: "list", style: "numbered", items: ["", "", ""] },
			{ id: "h-disc", kind: "heading", level: 2, icon: "💬", text: "Discussão" },
			{ id: "t-disc", kind: "text", text: "- " },
			{ id: "h-dec", kind: "heading", level: 2, icon: "✅", text: "Decisões" },
			{ id: "t-dec", kind: "text", text: "- " },
			{ id: "h-act", kind: "heading", level: 2, icon: "🚦", text: "Action Items" },
			{ id: "task-act", kind: "tasks-placeholder", dueDateOffset: 7 },
		],
		createdAt: NOW,
		updatedAt: NOW,
	},
	{
		id: "weekly-status",
		name: "Weekly Status Report",
		icon: "📊",
		description: "Relatório semanal executivo (preenchido pelo Atlas)",
		category: "report",
		variables: [
			{ key: "semana", label: "Semana", required: true },
		],
		blocks: [
			{
				id: "fm",
				kind: "frontmatter",
				fields: {
					type: "weekly-status",
					week: "{{semana}}",
					status: "draft",
					generated_by: "atlas",
					tags: "[report, weekly]",
				},
			},
			{ id: "h1", kind: "heading", level: 1, icon: "📊", text: "Weekly Status — W{{semana}}" },
			{ id: "h-hi", kind: "heading", level: 2, icon: "🟢", text: "Highlights" },
			{ id: "list-hi", kind: "list", style: "numbered", items: ["", "", ""] },
			{ id: "h-lo", kind: "heading", level: 2, icon: "🔴", text: "Lowlights" },
			{ id: "t-lo", kind: "text", text: "- " },
			{ id: "h-rag", kind: "heading", level: 2, icon: "🚦", text: "RAG Status" },
			{
				id: "code-rag",
				kind: "code",
				lang: "dataview",
				code: 'TABLE rag, comment, owner\nFROM "04_Projects"\nWHERE rag\nSORT rag DESC',
			},
			{ id: "h-risks", kind: "heading", level: 2, icon: "⚠️", text: "Top Risks" },
			{ id: "t-r", kind: "text", text: "- " },
			{ id: "h-next", kind: "heading", level: 2, icon: "🎯", text: "Próxima semana" },
			{ id: "t-n", kind: "text", text: "- " },
		],
		createdAt: NOW,
		updatedAt: NOW,
	},
];
